global:
  smtp_smarthost: 127.0.0.1:25
  smtp_from: root@localhost
route:
  group_by: ['alertname']
  repeat_interval: 1h
  receiver: ec2-user
  routes:
  - match_re:
      alertname: (serviceDown|.*Usage$)
    receiver: root
    repeat_interval: 1d
    group_by: [alertname, instance]
    continue: true
  - match:
      severity: critical
    receiver: operator
    continue: false
receivers:
- name: 'root'
  email_configs:
  - send_resolved: false
    to: root@localhost
    html: ''
- name: 'operator'
  email_configs:
  - send_resolved: false
    to: operator@localhost
    html: ''
- name: 'ec2-user'
  email_configs:
  - send_resolved: false
    to: ec2-user@localhost
    from: ec2-user@localhost
    html: ''
