global:
  smtp_smarthost: 127.0.0.1:25
route:
  group_by: ['alertname']
  repeat_interval: 1h
  receiver: ec2-user
  routes:
  - receiver: root
    group_by: ['alertname', 'instance']
    match:
      alertname: (serviceDown|*Usage)
    continue: true
  - receiver: operator
    match:
      severity: critical
    continue: false
receivers:
- name: 'root'
  email_configs:
  - send_resolved: false
    to: root@localhost
    from: ec2-user@localhost
    html: ''
- name: 'operator'
  email_configs:
  - send_resolved: false
    to: operator@localhost
    from: ec2-user@localhost
    html: ''
- name: 'ec2-user'
  email_configs:
  - send_resolved: false
    to: ec2-user@localhost
    from: ec2-user@localhost
    html: ''
