route:
  group_by: ['alertname']
  repeat_interval: 1h
  routes:
  - receiver: critical
    group_by: ['alertname', 'instance']
    match:
      severity: critical
    continue:false
  - receiver: warning
    match:
      severity: warning
    continue:false   
receivers:
- name: 'critical'
  email_configs:
  - send_resolved: false
    to: ec2_user@localhost
    from: ec2_user@localhost
    html: ''
- name: 'warning'
  email_configs:
  - send_resolved: false
    to: ec2_user@localhost
    from: ec2_user@localhost
    html: ''
